name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
   contents: read

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: "adopt"

    - name: Change directory to ./server
      run: cd ./server    

    - name: Build with Gradle
      run: |
            chmod +x ./gradlew
            ./gradlew clean build -x test

    - name: Docker build & push to docker repo
      run: |
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            docker build -f Dockerfile -t ${{ secrets.DOCKER_REPO }} .
            docker push ${{ secrets.DOCKER_REPO }}
          
