name: Server Docker Image CI

on:
  push:
    branches: [ "server" ]
  pull_request:
    branches: [ "server" ]

permissions:
   contents: read

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: "adopt"
  

    - name: Build with Gradle
      run: |
            cd ./server
            chmod +x ./gradlew
            ./gradlew clean build -x test

    - name: Docker build & push to docker repo
      run: |
            cd ./server
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            docker build -f Dockerfile -t ${{ secrets.DOCKER_REPO }} .
            docker push ${{ secrets.DOCKER_REPO }}
          
    - name: Deploy to server
      uses: appleboy/ssh-action@master
      id: deploy
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_KEY }}
        envs: GITHUB_SHA
        script: |
               docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
               sudo docker pull ${{ secrets.DOCKER_REPO }}:latest
               sudo docker rmi $(sudo docker images -f "dangling=true" -q) || true
               sudo docker-compose up -d
